name: consistory
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.4
  - cryptography=41.0.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.52
  - cuda-runtime=12.1.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_core=5.5.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.0.34
  - libcurand=10.3.4.52
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.40
  - prompt_toolkit=3.0.40
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.1.0=py3.10_cuda12.1_cudnn8.9
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - traitlets=5.13.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - wcwidth=0.2.9
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.30.0
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.41.2.post2
      - bleach==6.1.0
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.14.7
      - defusedxml==0.7.1
      - diffusers==0.23.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - fastjsonschema==2.19.1
      - fonttools==4.44.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.17.3
      - imageio==2.32.0
      - importlib-metadata==6.8.0
      - isoduration==20.11.0
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - matplotlib==3.8.1
      - mistune==3.0.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - opencv-python==4.8.1.78
      - overrides==7.7.0
      - pandas==2.1.3
      - pandocfilters==1.5.1
      - prometheus-client==0.20.0
      - protobuf==4.25.1
      - psutil==5.9.6
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.5
      - pyparsing==3.1.1
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - referencing==0.35.1
      - regex==2023.10.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.4.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - send2trash==1.8.3
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - terminado==0.18.1
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.3.0
      - tokenizers==0.14.1
      - tomli==2.0.1
      - tornado==6.4
      - tqdm==4.66.1
      - transformers==4.35.0
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2023.3
      - uri-template==1.3.0
      - wandb==0.16.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xformers==0.0.22.post7
      - xxhash==3.4.1
      - yarl==1.9.2
      - zipp==3.17.0
